## Numpy
Es una biblioteca de Python utilizada para lidiar con una gran cantidades de datos homogeneos como se hace Matlab.

### importando la libreria Numpy
Hay tres formas de importar esa librería:
* **import numpy:** Es una opción que tiene su incoveniente, ya que siempre que necesitamos utilizar una función de esa librería, hay que poner el nombre de la librería antes de la función.

* **import numpy as np:** Es otra forma de importar la librería, pero la renombra para facilitar su uso. Es la opción más utilizada, ya que es mas fácil escribir **_np_** que escribir **_numpy_**.

* **from numpy import *:** Es la tercera forma que aqui es muy cómodo utilizar porque no hace falta anteponer el nombre de la librería, pero el incoveniente es que se el nombre de una función de esa librería puede coincidir con el nombre de otra función que pertenece a otra librería.

In [1]:
import numpy as np #importando la librería numpy

In [4]:
L1 = [1,2,3,4,5,6,7,8] #Ejemplo de crear una lista

Con **numpy** puedo importar esa lista y utilizarla.

In [5]:
x1 = np.array(L1)#Insertando una lista en un array de numpy

In [6]:
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

Tambien se puede especificar el tipo de dato que quiere albergar dentro del array de numpy.

In [7]:
x2 = np.array(L1, dtype="float32")

In [8]:
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

Los tipos más comunes de **dtype** son:
* **bool_ :** Datos boleanos.

* **int_ :** Datos del tipo doble enteros de C.

* **intc :** Datos del tipo enteros de C.

* **intp :** Datos enteros utilizados para indexar.

* **int8, int16, int32, int64 :** Son datos enteros de 8 hasta datos de 64 bits respectivamente.

* **uint8, uint16, uint32, uint64 :** Son datos enteros sin signo de 8 hasta 64 bits respectivamente.

* **float_ :** Datos de tipo float de 64 bits.

* **float_16 :** Datos de tipo float de media precisión donde tiene un bit para el signo, cinco bits para el exponente y 10 bits para mantiza.  

* **float_32 :** Datos de tipo float de precisión normal donde tiene un bit para el signo, ocho bits para el exponente y 23 bits para la mantiza.

* **float_64 :** Datos de tipo float de precisión alta, tambien conocido como doble donde tiene un bit para el signo, once bits para el exponente y cincuenta y dos bits para la mantiza.

La representación sería (+/-$9999999999e^{99999}$) ejemplo de representación de un float_16

* **complex_ :** Datos de tipo complejos de 64, pero no es 64 bits, esos 64 representa 32 bits para la parte real y 32 para la parte imaginaria. ($a+bi, a,b \in$ float)

* **complex64, complex128 :** El mismo que el anterior, pero sólo sube el número de bits de representación. Acuerdate que la parte real es la mitad y la parte imaginaria ocupa la otra mitad. ($a+bi, a,b \in$ float_)


## Matrices

### Inicializar una matriz con valores definidos
Inicializar una matriz de ceros con 3 filas y 4 columnas utilizando la librería **numpy**

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

inicializar una matriz de unos con 4 filas y 3 columnas con **numpy**

In [10]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Inicializar un array de 10 elementos consecutivos.

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Inicializar un array que empieze en 3 y termine en 12 del tipo float

In [12]:
np.arange(3,12, dtype = np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Inicializar un array que empieza en 4 termina en 5 con intervalos de 0.1

In [13]:
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

Una función equivalente a **range** es **linspace** para crear un array que tiene valor de inicio, final y el espaciado entre ellos de forma fija.

In [14]:
np.linspace(1,7,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

como se puede observar ha creado 12 posiciones dentro del intervalo de 1 y 7

#### Matriz identidad

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Para redimencionar una matriz

Por ejemplo, modificar una matriz de 8 filas y 3 columnas a otra matriz de 6 filas y 4 columnas

In [17]:
x = np.zeros((8,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
x.reshape((6,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Tambien se pude transformar un array en una matriz.

In [23]:
y = np.arange(24)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
y.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Nota importante:** Sólo funciona si el producto de la fila por la columna de los valores sea igual al número de elementos que tiene el array o matriz que se va modificar. **Ejemplo:** El array anterior tiene 24 elementos y al redimencionar el números de filas es 6 y el número de columnas es 4 entonces $6\times 4=24$ 

Se puede transformar una matriz en un vector de la misma forma que un vector a una matriz, pero con la función **ravel** de **numpy**

In [28]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
np.ravel(x)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

En muchas ocasiones no se puede modificar la estructura original, entonces para eso se utiliza una función de numpy llamada **flatten** para hacer una copia de lo original y aplana el resultado como se fuera un ravel, pero la estructura original se queda sin modificar.

In [30]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Transporner una matriz


In [31]:
np.transpose(x)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

### Redimensionar una matriz partiendo de uno hecho

In [32]:
np.resize(x,(5,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  1,  2],
       [ 3,  4,  5]])

### Ejercicios:

1. Crear un array de datos con valores entre 5 y 120.

2. Crear una matriz 4x4 con los valores desde 0 hasta 15.

3. Crear la identidad 7x7.

4. Crear un array de 20 elementos y transformarlos en una matriz 5x4.

5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme.

### Propiedades de los arrays de numpy

In [2]:
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
x.ndim #Con numpy se mira la dimensión del array (matriz)

2

In [5]:
x.size#Con numpy se mira el tamaño asi.

12

In [6]:
x.dtype #Saber el tipo de datos almacenados en el array

dtype('int32')

In [8]:
x.itemsize #Saber el número de bytes de cada elemento de la matriz

4

In [9]:
x.data #El buffer en memoria que contiene los elementos de la matriz

#### Acceder los elementos de los arrays en numpy
No difiere mucho de como acceder a los elementos lista o tupla de python.

In [10]:
x[2]

array([ 8,  9, 10, 11])

In [13]:
x[2,1] #Fila 2 y colunma 1.

9

In [12]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
y = np.arange(12) #Crea una lista de 12 elementos.
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
y[3:8] #Seleccionar un sub-array de la posición 3 a la 8 del array original.

array([3, 4, 5, 6, 7])

In [19]:
y[1:7:2]

array([1, 3, 5])

In [21]:
x = np.arange(50)

#### Acceder los elementos por posición booleana

In [22]:
x[x > 30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [23]:
cond = (x < 25)
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [24]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

sustituir parcialmente elementos de un array. Por ejemplo, sustituir los elementos de la posición 12 hasta la posición 24 por el número 1.

In [25]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

Sustituir un grupo de valores (subarray) en un rango de posiciones de un array más grande.

In [32]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [33]:
x[13:16] = [6,9,12]

In [34]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  6,  9, 12, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Copias y vistas de arrays
Unos de los mayores problemas que se encuentra en la hora de lidiar con los array es saber si estas lidiando con el array original o con la copia. Para eseo vamos a distinguir tres casos diferentes:

* **Cuando se hace una asignación**, es decir, por no hacer una copia al modificar una que esta apuntando al mismo espacio de memoria, apesar de tener nombres distintos, ese se ve afectado también. **Ejemplo:**

In [38]:
x = np.arange(10)#Crea un array (x).
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
y = x #Crea un array (y) desde el array (x)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
y.shape = (2,5)#Modifico el array (y)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
# Pero el array (x) tambien se ha visto afectado
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Eso pasa por que no se ha hecho una copia del array (**x**). Solamente ha creado el array (**y**) asignando la dirección de memoria del array (**x**).

Para solucionar hay que hacer una copia y despues comprobar.

In [50]:
z = x.copy() #Haciendo una copia de x en z
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
z is x #Preguntando si z es un x

False

Como se puede comprobar, apesar de tener el mismo contenido, no es el mismo array.

#### Vistas
Las vistas no son una copia, si comparte parte de información comun entre los arrays involucrados.

In [51]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
t = x.view()

In [53]:
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
t.shape = (5,2)

In [55]:
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Como se puede observar, al modificar la vista no ha afectado el array original. Es bueno utilizar una vista porque así no hace falta estar creando variables constantemente para ir ocupando memoria.

# Funciones universale (ufunc)
Con el uso de las funciones universales no hara falta estar creando un bucle para recoger los elementos de un array. Operaciones universales se dividen en dos tipos:

* Operaciones **Unarias**: sqrt, sin, cos, **2
* Operacioes **Binarias**: maximum, minimum

## Ejemplos de operacines **Unarias**:
* Operaciones elementales:

In [59]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x + 3 #Sumar 3 en todos los elementos del array.


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
x - 3 #Restar 3 en todos los elementos del array.

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [64]:
x * 3 #Multiplicar por 3 todos los elementos del array.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [65]:
x / 3 #Dividir por 3 todos los elementos del array.

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

* Operaciones trigonométicas

In [66]:
alpha = np.linspace(0, 2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [68]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [69]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [70]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

* Exponenciales y logaritmos

In [71]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [72]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [73]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

In [74]:
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [75]:
np.log(x)

C:\Users\weltonvs\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

* Estadísticos 

Aqui calcula la suma, pero no hay posiciones sin datos provocará un error. Esos datos que provocan errores pueden ser los de tipo NAN. $$\text{Sumatorio:}\sum_{i=1}^{n}x_i$$

In [76]:
np.sum(x) 

45

Para solucionar el problema, **numpy** cubre ese problema en casi todas sus funciones llamando la función pertinente que elimina los datos Nan de los calculos.

In [77]:
np.nansum(x)

45

$$\text{Producto: }\prod_{i=1}^{n}x_i$$

In [78]:
np.prod(x)

0

$$\text{Media artimética: }\frac{1}{n}\cdot\sum_{i=1}^{n}x_i$$

In [79]:
np.mean(x)

4.5

$$\text{Calcular la mediana}$$

In [80]:
np.median(x)

4.5

$$\text{Calcular el mínimo valor}$$

In [81]:
np.min(x)

0

$$\text{Calcular el máximo valor}$$

In [82]:
np.max(x)

9

$$\text{Desviación típica: }$$

In [83]:
np.std(x)

2.8722813232690143

$$\text{Varianza: }$$

In [84]:
np.var(x)

8.25

$$\text{Posición del valor mas pequeño}$$

In [85]:
np.argmin(x)

0

$$\text{Posición del valor mas grande}$$

In [86]:
np.argmax(x)

9

$$\text{Percentiles}$$

In [91]:
np.percentile(x, q = 0.95)# Con cuartil de 95%

0.08549999999999999

In [92]:
np.percentile(x, q = 0.5) # Con cuartil de 50%

0.045

In [93]:
np.percentile(x, q = 0.25) # Con cuartil de 25%

0.0225

Generar una matriz con números aleatorios

In [96]:
z = np.random.random((3,5))#Matriz de números aleatorios de 3 filas y 5 columnas
z

array([[8.14871145e-01, 7.39989807e-02, 3.17215111e-01, 3.68824530e-02,
        8.88722002e-01],
       [8.18704699e-01, 5.76925276e-04, 2.56794663e-01, 8.99885541e-01,
        6.50466436e-01],
       [4.88662570e-01, 6.52251925e-01, 5.14905412e-01, 2.80350852e-01,
        1.88269738e-01]])

In [98]:
z.sum()# Suma de todos los elementos de z

6.8825584522031145

In [99]:
z.sum(axis = 0)#Suma por columnas

array([2.12223841, 0.72682783, 1.08891519, 1.21711885, 1.72745817])

In [101]:
z.sum(axis = 1)#Suma por filas

array([2.13168969, 2.62642826, 2.1244405 ])

Para resetear la semilla de los número aleatorios.

In [102]:
np.random.seed(2019)

# Algebra lineal con numpy
## Matrices
* Vector Fila

In [103]:
row = [1,2,3]
row

[1, 2, 3]

* Vector columna

In [104]:
col = [[1],[2],[3]]
col

[[1], [2], [3]]

* Uma matriz

In [105]:
M = [[1,2,4], [4,5,6], [7,8,9]]
M

[[1, 2, 4], [4, 5, 6], [7, 8, 9]]

### Acceder las posiciones de un array

In [106]:
M[0][0]# Primer elemento de la matriz

1

In [107]:
M[1][1]# Elemento de la fila 1 y columna 1

5

In [108]:
M[0] # Todos los elementos de la fila 1

[1, 2, 4]

### Utilizando la librería **numpy**

In [109]:
import numpy as np #Importando la librería numpy y creando un álias para facilitar el trabajo llamado np

In [110]:
# Crear una matriz con numpy
Matriz = np.array([[1, 2, 4], [4, 5, 6], [7, 8, 9]])
Matriz

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

Con numpy puedo crear e indicar el tipo de dato que quiero.

In [112]:
# Crear una matriz con numpy de tipo complejo.
Matriz = np.array([[1, 2, 4], [4, 5, 6], [7, 8, 9]], dtype = complex)
Matriz

array([[1.+0.j, 2.+0.j, 4.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [114]:
# Crear una matriz con numpy de tipo entero.
Matriz = np.array([[1, 2, 4], [4, 5, 6], [7, 8, 9]], dtype = int)
Matriz

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
# Crear una matriz con numpy de tipo float.
Matriz = np.array([[1, 2, 4], [4, 5, 6], [7, 8, 9]], dtype = float)
Matriz

array([[1., 2., 4.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [116]:
#Saber el número de filas y columnas de una matriz
np.shape(Matriz)

(3, 3)

### Sumar Matrices

In [117]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,0],[1,-1]])

In [118]:
A + B

array([[4, 2],
       [4, 3]])

### Multiplicar Matrices

In [120]:
A * B #Multiplicación de una matriz por otra matriz

array([[ 3,  0],
       [ 3, -4]])

In [123]:
A.dot(B) #Multiplicación de filas por columnas

array([[ 5, -2],
       [13, -4]])

### Matriz Transpuesta

In [124]:
A.transpose()#Matriz transpuesta de A

array([[1, 3],
       [2, 4]])

### Matriz Inversa

In [125]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Determinando de una Matriz

In [127]:
np.linalg.det(A)

-2.0000000000000004

Responde a las preguntas incorporando el codigo en Python que demuestre que lo has practicado correctamente

Preguntas de esta tarea

1. Crea una función que reciba los tres coeficientes a, b y c para resolver una ecuación de segundo grado. Muestra la solución por pantalla y ayúdate de la librería Math para acceder a la función raíz cuadrada.

2. Crea una función que lea una frase de teclado y nos diga si es o no un palíndromo (frase que se lee igual de izquierda a derecha o al revés como por ejemplo La ruta nos aportó otro paso natural.)

3. Crea un diccionario que tenga por claves los números del 1 al 10 y como valores sus raíces cuadradas

4. Crea un diccionario que tenga como claves las letras del alfabeto castellano y como valores los símbolos del código morse (los tienes todos en la Wikipedia). A continuación crea un programa que lea una frase del teclado y te la convierta a Morse utilizando el diccionario anterior.

5. Crea una función que dados dos diccionarios nos diga que claves están presentes en ambos.

6. Crea una función que dado un número N nos diga si es primo o no (tiene que ir dividiendo por todos los números x comprendidos entre 2 y el propio número N menos uno y ver si el cociente de N/x tiene resto entero o no).

7. Investiga la documentación de la clase string y crea un método que lea una frase del teclado y escriba la primera letra de cada palabra en Mayúscula.

8. Crea una función que calcule el máximo común divisor de dos números introducidos por el usuario por teclado.

9. Investiga el Cifrado del César y crea una función que lo reproduzca en Python. Cada letra del mensaje original se desplaza tres posiciones en el alfabeto estándar. La A se convierte en la D, la B se convierte en la E, la C se convierte en la F... y cuando se acaba el alfabeto se le vuelve a dar la vuelta: la X se convierte en la A, la Y en la B y la X en la C. Los números no sufren ninguna modificación.

10. Dado una lista de nombres de persona, escribe un algoritmo que los ordene de tres formas diferentes:

    A. De forma alfabética

    B. De forma alfabética invertida

    C. De nombre más corto al más largo.